/**
 * @file IPlanBuilder.h
 * @brief Abstract interface for the Plan Builder.
 *
 * IPlanBuilder is responsible for transforming a semantic ASTNode tree into an
 * immutable IExecutionPlan blueprint. It owns all graph construction: step creation,
 * edge wiring, node ID generation, ExecutionPolicy injection, and metadata assembly.
 * Neither IntentCompiler nor SemanticOrchestrator may construct runtime objects directly.
 *
 * ESP-Claw Platform — Phase E (Intent Compiler & End-to-End Integration)
 */

#pragma once

#include "compiler/IntentAST.h"
#include "plan/IExecutionPlan.h"
#include "core/LogicalDevice.h"
#include "core/ExecutionPolicy.h"
#include "IDeviceController.h"
#include <memory>
#include <string>

namespace NetDiscovery {
namespace compiler {

/**
 * @brief Context provided to IPlanBuilder::Build() by SemanticOrchestrator.
 *
 * Contains the resolved runtime context needed to construct step objects
 * (device pointer, controller pointer, execution policy).
 */
struct PlanBuildContext {
    /// Primary resolved device. Must be non-null for plans containing ActionStep nodes.
    const LogicalDevice* resolvedDevice{nullptr};

    /// Selected controller for the resolved device. Must be non-null for ActionStep nodes.
    IDeviceController* selectedController{nullptr};

    /// Execution policy to apply to the generated plan.
    ExecutionPolicy policy{ExecutionPolicy::Interactive()};

    /// Unique plan identifier. Generated by SemanticOrchestrator (e.g. based on timestamp).
    std::string planId;

    /// Human-readable plan name for diagnostics.
    std::string planName;
};

/**
 * @brief Transforms a semantic ASTNode tree into an immutable IExecutionPlan.
 *
 * Implementation contract:
 *   - Owns all runtime object construction: ActionStep, DelayStep, BranchStep, LoopStep,
 *     ParallelStep, ExecutionEdge, ExecutionNode, DAGExecutionGraph, ExecutionPlan.
 *   - Must not perform device matching, controller selection, or NLP parsing.
 *   - Must produce a valid, verifiable IExecutionPlan (must pass StaticPlanValidator).
 *   - Must inject a DelayStep after any ASTNode with waitAfter > 0ms.
 *   - Must resolve conditionExpression strings into IPredicate instances for BranchStep.
 *   - Returns nullptr on structural errors (e.g. empty AST root).
 */
class IPlanBuilder {
public:
    virtual ~IPlanBuilder() = default;

    /**
     * @brief Build an immutable ExecutionPlan from a resolved ASTNode tree.
     * @param root    Root of the semantic AST produced by IIntentCompiler.
     * @param ctx     Build context containing device, controller, policy, and plan ID.
     * @return Shared pointer to an immutable IExecutionPlan blueprint, or nullptr on error.
     */
    virtual std::shared_ptr<Plan::IExecutionPlan> Build(
        const ASTNode&          root,
        const PlanBuildContext& ctx
    ) const = 0;
};

} // namespace compiler
} // namespace NetDiscovery
